version: '3.9'
services:
  mysql:
    image: mysql:8.0
    container_name: mysql-tarefas
    environment:
      MYSQL_ROOT_PASSWORD: senha
      MYSQL_DATABASE: tarefasdb
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    command: --default-authentication-plugin=mysql_native_password
volumes:
  mysql_data:
